### PR TITLE
Added several fixes to the logic of adding/removing likes in a chat message

### LINKED ISSUE #2396: Add likes to message in Chat module

### PR DESCRIPTION
**Pull request by Maryna-511750**
## Summary Of Changes :fire:
- Added several fixes to the logic of adding/removing likes in a chat message
- Added Set(UserDto) likes field to ChatMessageWithFileDto to display users who liked the message
- Created UserDto to concisely display user information
- Fixed LazyInitializationException when loading Set(Participant) likes field in ChatMessage entity from database

## Issue Link
[#2396](https://github.com/ita-social-projects/GreenCity/issues/2396)

### CODE REVIEW

**Review by HelenSotnik — APPROVED** [review]

**Review by lukovskyj — APPROVED** [review]

File: chat/src/test/java/greencity/mapping/ChatMessageWithFileDtoMapperTest.java [hunk 1]
```diff
@@ -24,13 +29,48 @@ void init() {
...
+
+    @Test
+    void convertWithNullFields() {
+        chatMessage.setFileName(null);
+        chatMessage.setFileType(null);
+        chatMessage.setFileUrl(null);
+
+        expected.setFileName(null);
+        expected.setFileType(null);
+        expected.setFileUrl(null);
```
Comment (VinuVicho) [inline chat/src/test/java/greencity/mapping/ChatMessageWithFileDtoMapperTest.java]: Recommendation: do not modify many fields, just create "expected" in method with all required data. 
It also can lead to some problems when tests are launched in parallel and using class variable.

**Review by KizerovDmitriy — APPROVED** [review]
